# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imdb/file_formats/AnnoList.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imdb/file_formats/AnnoList.proto',
  package='protobuf_annolist',
  serialized_pb=_b('\n imdb/file_formats/AnnoList.proto\x12\x11protobuf_annolist\"B\n\tAttribute\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x05\x12\x0c\n\x04\x66val\x18\x03 \x01(\x02\x12\x0e\n\x06strval\x18\x04 \x01(\t\"\"\n\tIdStrPair\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01s\x18\x02 \x01(\t\"j\n\rAttributeDesc\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\x05\x12\x30\n\nval_to_str\x18\x04 \x03(\x0b\x32\x1c.protobuf_annolist.IdStrPair\"A\n\tAnnoPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x12\n\nis_visible\x18\x04 \x01(\x08\"\xc5\x01\n\x08\x41nnoRect\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\x12\n\n\x02id\x18\x06 \x01(\x05\x12\x10\n\x08track_id\x18\x0b \x01(\x05\x12/\n\tattribute\x18\x0c \x03(\x0b\x32\x1c.protobuf_annolist.Attribute\x12+\n\x05point\x18\x0e \x03(\x0b\x32\x1c.protobuf_annolist.AnnoPoint\"o\n\nAnnotation\x12\x11\n\timageName\x18\x01 \x01(\t\x12)\n\x04rect\x18\x02 \x03(\x0b\x32\x1b.protobuf_annolist.AnnoRect\x12\x10\n\x08imgWidth\x18\x03 \x01(\x05\x12\x11\n\timgHeight\x18\x04 \x01(\x05\"w\n\x08\x41nnoList\x12\x31\n\nannotation\x18\x01 \x03(\x0b\x32\x1d.protobuf_annolist.Annotation\x12\x38\n\x0e\x61ttribute_desc\x18\x02 \x03(\x0b\x32 .protobuf_annolist.AttributeDescB\x0c\x42\nAnnoListPb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='protobuf_annolist.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf_annolist.Attribute.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='protobuf_annolist.Attribute.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fval', full_name='protobuf_annolist.Attribute.fval', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strval', full_name='protobuf_annolist.Attribute.strval', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=121,
)


_IDSTRPAIR = _descriptor.Descriptor(
  name='IdStrPair',
  full_name='protobuf_annolist.IdStrPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf_annolist.IdStrPair.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='protobuf_annolist.IdStrPair.s', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=157,
)


_ATTRIBUTEDESC = _descriptor.Descriptor(
  name='AttributeDesc',
  full_name='protobuf_annolist.AttributeDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf_annolist.AttributeDesc.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf_annolist.AttributeDesc.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='protobuf_annolist.AttributeDesc.dtype', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val_to_str', full_name='protobuf_annolist.AttributeDesc.val_to_str', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=265,
)


_ANNOPOINT = _descriptor.Descriptor(
  name='AnnoPoint',
  full_name='protobuf_annolist.AnnoPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protobuf_annolist.AnnoPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='protobuf_annolist.AnnoPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf_annolist.AnnoPoint.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_visible', full_name='protobuf_annolist.AnnoPoint.is_visible', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=332,
)


_ANNORECT = _descriptor.Descriptor(
  name='AnnoRect',
  full_name='protobuf_annolist.AnnoRect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='protobuf_annolist.AnnoRect.x1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y1', full_name='protobuf_annolist.AnnoRect.y1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x2', full_name='protobuf_annolist.AnnoRect.x2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y2', full_name='protobuf_annolist.AnnoRect.y2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='protobuf_annolist.AnnoRect.score', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf_annolist.AnnoRect.id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='protobuf_annolist.AnnoRect.track_id', index=6,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='protobuf_annolist.AnnoRect.attribute', index=7,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point', full_name='protobuf_annolist.AnnoRect.point', index=8,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=532,
)


_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='protobuf_annolist.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageName', full_name='protobuf_annolist.Annotation.imageName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rect', full_name='protobuf_annolist.Annotation.rect', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgWidth', full_name='protobuf_annolist.Annotation.imgWidth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgHeight', full_name='protobuf_annolist.Annotation.imgHeight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=645,
)


_ANNOLIST = _descriptor.Descriptor(
  name='AnnoList',
  full_name='protobuf_annolist.AnnoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='annotation', full_name='protobuf_annolist.AnnoList.annotation', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_desc', full_name='protobuf_annolist.AnnoList.attribute_desc', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=766,
)

_ATTRIBUTEDESC.fields_by_name['val_to_str'].message_type = _IDSTRPAIR
_ANNORECT.fields_by_name['attribute'].message_type = _ATTRIBUTE
_ANNORECT.fields_by_name['point'].message_type = _ANNOPOINT
_ANNOTATION.fields_by_name['rect'].message_type = _ANNORECT
_ANNOLIST.fields_by_name['annotation'].message_type = _ANNOTATION
_ANNOLIST.fields_by_name['attribute_desc'].message_type = _ATTRIBUTEDESC
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['IdStrPair'] = _IDSTRPAIR
DESCRIPTOR.message_types_by_name['AttributeDesc'] = _ATTRIBUTEDESC
DESCRIPTOR.message_types_by_name['AnnoPoint'] = _ANNOPOINT
DESCRIPTOR.message_types_by_name['AnnoRect'] = _ANNORECT
DESCRIPTOR.message_types_by_name['Annotation'] = _ANNOTATION
DESCRIPTOR.message_types_by_name['AnnoList'] = _ANNOLIST

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTE,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.Attribute)
  ))
_sym_db.RegisterMessage(Attribute)

IdStrPair = _reflection.GeneratedProtocolMessageType('IdStrPair', (_message.Message,), dict(
  DESCRIPTOR = _IDSTRPAIR,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.IdStrPair)
  ))
_sym_db.RegisterMessage(IdStrPair)

AttributeDesc = _reflection.GeneratedProtocolMessageType('AttributeDesc', (_message.Message,), dict(
  DESCRIPTOR = _ATTRIBUTEDESC,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.AttributeDesc)
  ))
_sym_db.RegisterMessage(AttributeDesc)

AnnoPoint = _reflection.GeneratedProtocolMessageType('AnnoPoint', (_message.Message,), dict(
  DESCRIPTOR = _ANNOPOINT,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.AnnoPoint)
  ))
_sym_db.RegisterMessage(AnnoPoint)

AnnoRect = _reflection.GeneratedProtocolMessageType('AnnoRect', (_message.Message,), dict(
  DESCRIPTOR = _ANNORECT,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.AnnoRect)
  ))
_sym_db.RegisterMessage(AnnoRect)

Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), dict(
  DESCRIPTOR = _ANNOTATION,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.Annotation)
  ))
_sym_db.RegisterMessage(Annotation)

AnnoList = _reflection.GeneratedProtocolMessageType('AnnoList', (_message.Message,), dict(
  DESCRIPTOR = _ANNOLIST,
  __module__ = 'imdb.file_formats.AnnoList_pb2'
  # @@protoc_insertion_point(class_scope:protobuf_annolist.AnnoList)
  ))
_sym_db.RegisterMessage(AnnoList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\nAnnoListPb'))
# @@protoc_insertion_point(module_scope)
